pico-8 cartridge // http://www.pico-8.com
version 41
__lua__
-- genuary #5 2024
-- in the style of vera molnar
-- by carson kompon

cls(0)
?"\^!5f10?●ˇ●ˇ█"
cols=6
o={}
f=0

function _update60()	
	if(f%2==0)spawn()
	
	for s in all(o)do
		s:update()
	end
	
	for i=0,299do
		local x=rnd(128)
		local y=rnd(128)
		pset(x,y,0)
	end
	
	f+=1
end

function spawn()
	local s={
		x=flr(rnd(4))*32+16,
		y=flr(rnd(4))*32+16,
		c=rnd(cols),
		d=flr(rnd(4))/4,
		s=1,--rnd(2),
		r=flr(rnd(8))+3,
		f=8+flr(rnd(20)),
		m=10,
		t=rnd({-.25,.25}),
		a=rnd(.02)-.01,
		update=function(s)
			local lx=s.x
			local ly=s.y
			s.x+=cos(s.d)*s.s
			s.y+=sin(s.d)*s.s
			line(lx,ly,s.x,s.y,s.c)
			if s.m%s.f==0then
				s.d+=s.t+s.a
				s.r-=1
				if(s.r<=0)del(o,s)
			end
			s.m+=1
		end
	}
	local d=s.d-(.25*sgn(s.t))
	local z=s.f/2
	s.x+=cos(d)*z
	s.y+=sin(d)*z
	s.a*=s.f/64
	add(o,s)
end
__gfx__
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00700700006600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00077000666606600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00077000660666600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00700700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
__label__
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffflllllllllflflllfffffffffffffmmffffffffffffffffffffffffffffffff
ffffffmffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffmffffmmfmffmfmffffffffflffllflfffffffffffffffff
ffffffflflfflllffffffffflfffffffffffffffffffffffffffffffffffffffffffffmmmmmmmmffmffffffffffffffmfffffffffffflfflffflllfffllfffff
ffffffllllfffffffffffffffffffffffffffffflffllffffffffffffffffffffffffffffffffffffffffffffffgfffmffffffmfffmmmmmfffffffffffflffff
fffffflllllllllllffmmmfmmfffffffffffffflfffflflflffllffllffffffffffmmmmmmmfmmmmmmmfmfffffffffffffffffffgfgggflfllllllllffflfffff
mfffflmmmmmmffmfmffllllllflffffffffffffffffffffffffffflfflfffffffffmfffffffffffffffffffffffmffffffffgllllllllggggfggfgfgfggglfff
fflfflffllllllflffffffffffflflfffffffffffmffffffflffffflfffffffffffmfffffffffffffffffffffffffmfmffffflfffffflffffffffffffmfglfff
ffffflffffffffllfflllllllffffffffffffffflmlllllfffffllllfflffffffffmfffffffffffffffffffffffffmfmffffglfffffffffffffffffffflglfff
fflfflfflffffffffffffffffffffffffffffffffmffffffffffffgllffffffffffmffmfffffffffffffffffffffffffffffflfffffffffffffffffffflglfff
ffffflfffffffffffffffffflfffffffffffffflfmmmmmfmffmmmmmlfffffffffffmffmffffflflflllffffffffffmfmffffgffffffffffffffffffffmlglfff
ffffflfffffffffffffgfffflffflffffffffffffmffffffmffffffmfffffffffffmffffflffffffffffffflffffffffffffglmffffffffffffffffffflflfff
fffffffflffffffffffffffffffflffffffffffffmffffffmfffffgmfffffffffffffffffffffffffffffffffgffgffffffffffffffffffffffffffffmlflfff
fflfflfflffffffffffffffflffffffffffffffffmffffffmfffffffffffffffffffffffflffffffffffffflfffffmfffffffffffffffffffffffffffflflfff
ffffflfflffffffffffffffffffffffffffffffffmffgfffmffffffmffffffffffffffffffffffffffffffffffffgmffffflflfffffffffffffffffffffflfff
fffffffffffffffffffffffllffflffffffffffffmffffffmffffffflfffffffffffffffllffffffffffffffffffgffmfffffffffffffffffffffffffflfllff
fflffffllfffffffffffffflllfflffffffffffffmffgfffmffffgfflffffffffffffffflfffffffffffffffffffgffmffflffmfffffffffffffffffffffllff
fffffffflfffffffffffffffllflffffffffffffffffffffffffffffffffffffffffffffflffffffffffffffffffgmffffflflmfffffffffffffffffflfflfff
fffflfffffffffffffffffflfffffffffffffffffmffgfffmfffffffffffffffffffffffflfffffffffffffffffffmffmflffffffffffffffffffffffllflfff
fffffffllfffffffffffffffffflfffffffffffffmffgfmmmlfffffflffffffffffmffffflfffffffffffffffffffffffffffffffffffffffffffffffflflfff
ffffffffffffffffffffffffffflfffffffffffffmffgfffffffffffffffffffffgfffffflfffffffffffffffffffgfmmflfffmlffffffffffffffffflffffff
fffffffllllfffffffffffffflfffffffffffffffffffggfffffffggglffffffffffffffflfffffffffffffffffffgfffflfffmfffffffffffffffffflffffff
fffflffllfffffffffffffffflfffffffffffflffmfffffffffffgffffffffffffffffffflfffffffffffffffffffgfffflfflmfffffffffffffffffflfflfff
fffffffflflllflffflflllllfflffffffffffffffffffffffffffffffffffffffffffffflffffllllfffffffffffgfffflfffmfflfllffflffmffffflfflfff
fffffffmmfmfmfmffffflllfffflffffffffffffffffffffffffffffffffffffffffffffflflllffffffffffffffffffmflffffffffmffffffffflllllffflff
ffflffffffffffffffffffffflfffffffffffggggggggggggffffffffffffffffffffffmfffffffffffffffffffffgfffflffffffffffffffllflllfllflffff
ffffflffffflfffffffffffffffffffffffffffffffffffffffffffffffffffffffmfffffffffffffffffffffffffgfmfflfflfffffffffffffffffffflfffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffmmfffmmmfmffffffgfffflfflflllfffllflfllflffffffffff
fffffflfffllffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffgffffffffffffffgfggffffggfgfffffff
fffflffffffffflffffflfflffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffflff
fffffffffffffffffffffgffgglfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffgffffgggggggffggfffgfgffffffffffff
ffffffffffffffffggfffggffggfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffgflffgffflfllfffffffggfggfgffgffff
fffffffffffgggggfffffffffffgfffffffffffffffffffffffffffffffffffffffffffmmfffmfgffffgffffgmmmmffffffgfffffffffllfllflffffffffgfff
fffgfffggggfffffffffffffffgffffffffffffffffffffffffffffffffffffffffffffllffflflfffflfffffffffffffffgffffffffffffffffflflflflffff
fffggfgfffffffffffffffffffgfffffffffffffffffffffmfffmfmmfffmmfffffmfffffffffffmffffmflfffflfllllfffgffffffffffffffffffffffffgfff
ffggfffffffffffffffffffffffffffffffffgmmffmmmmfmmffmmmffffffffffffffffflffffffffffflfffffffffffflffgffffffffffffffffffffffffgfff
fffgffllffflffffffffffffffggffffffffffffffffffffgfffffffffffffmffflfflflfffffffffffffffffffffffffffgffffffffffffffffffffffffgfff
fffffffgfffffffffffffffffffgffffffffggmfffggffffffffffflfffffffmffffffffffffffmfmmmmmmlffffflffffffffffffllfffffffffffffffffffff
fffffflmmmmfmmfmmmmmmmmmfffgffffgfffgffffffffggffffffffgfgggfffmfflfffffffffmfffffffffffmffffffffffffffffffffflllfllllffffffgfff
ffffffffffffffffffffffffgflfffffffffffmffffffffffffffffffffffggmfflfffffffmfffffffmffmmfmffffffffffffffffffllllfffffffffffffffff
fffffffffflfffllflfffffffffffffffffffffffffffffffffffffffffffgfmmffffffllfmfffffffffffffffffffffffffffffffflgggfgggfgfgllflfffff
ffffgflmlffffffffffffffflflgfffffffffffffffffffffffffffffffffgfmmfffffflffmffffffffffmfffffffffflffgffffflfffffffffffffgffffffff
fffffflmfffffffffffffffffffgfffffffgffmfffffffffffgffffffffffgfmfflffflfffmffffffffffmffmfffffffffffffffffflffffffffmffgffffffff
ffffgffflfffffffffffffffffffffffffffffmffffffffffffffffffffffgfmmffffflfffmfffffffffffffffffffffffffffffffflfffffffffffgflffffff
fffffffmlfffffffffffffffffffffffffffffmfffffffffffffffgffffffgmmffffffffffmfffffffffffffffffffffffffffffflflfffffffffffgflffgfff
fffffffmlffffffffffffffffmffffffffffffmffffffffffffffffffffffffmfffffflfffmfffffffffffffffffffffffffffffffflfffffffffffgflffffff
ffffffgflffffffffffffffflfffgfffffffffmffffffffffffffffffffffgfmmffffffffffffffffffffmfffffffffffffgffffffflfffffffffffgffffgfff
fffffffflfffffffffffffflfffffffffffgffmmfffffffffffffffffgfffgmfmffffflffffffffffffffmfffffffffffffffffffffffffffffffflglfffgfff
fffffgfmlffffffffffffffflfffggfffffgffmmfffffffffffffffffffffgmfffffffffffmfffffffmmmmffmffffffffffffffffflfffffffffffffffffffff
fffffggffffffffffffffffflfffggffffggffmmfffffffffffffffffffffgmffffffflfffmfmfmfmffffffffffffffffffffffffllffffffffffflfffffgfff
fffffffflffffffffffffffflfffffffffffffmmfffffffffffffffffffffgmffffffflffffffffffffffffffffffffffffffffffllffmfffffffflflfffgfff
ffffffgflffffffffffffffflffffgfffffffffmfffffffffffffffffffffgmmmfflfflffffffffffffffffffffffffffffffffffflflfllfffffflflfffgfff
ffffffgmlffffffffffffffflffffffffffffffmffffffffffffffffffffggmmfffffffffffffffffffffffffffffffffffffffffflffffffffffffllfffgfff
ffffffgflffffffffffffffgffffgffffffgfffmffffffffffffffffffffgfmffffffflffffffffffffffffffffffffflfffffffffllffllflffffffffffffff
fffffffflggfffffffffffgglfgffffffffgfffmffffffffffffffffffffgfffmffffflfffffffmmfffffffffffffffflffgffffffflfflfffffllllffffgfff
fffffffflmfggfllllllllfllffffffffffffffmffffffffffffffffffffgffffffffffffffffffffffffflfmffflffffffffffggfgfffffffffffffffffffff
ffffffflflllllgfffffggggfffffffffffffffmffffffffffffffffffffgfmfffflfflfffffffffffffffffffffffffffffflffffffffgfffffggffggffffff
fffffffffffffffffffffffffffffffffffffffmffffffffffffffffffffgfmffffffflffffflflfffffflffflffffffffffflffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffgfffmfffffffffffffffmfmffgfmmmfffffllllllffffmmmmmmmmmffffffffffffllllfllllllllfflllfffffffff
fffffffffffffffffffffffffffffffffffffffmffmmmmmmmmmffmmmfmfmgfmmfmmfmmmmffmfllllllllllllfflfflfflfffffffffffffffffffffflfflfffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffgffffffffffffffmmfffmfmmmfmmfffffffffffffffffffflfffggggffffffffffff
fffffffffffffffffffffffffffffffffffgffffffffffffffffffffffffgffffffffffffffffffffffffffffffffffffffffffffffffflffffffflfffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffflffffffffffffffffffffffffffffffffmfff
fffffffffffffffffffffffffffffffffffgfffgffffffffffgfffffffgffffffflffflfffffflflllflflflllllffffffffmfffffffmmffffmfffmfffmfffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffflflfffffflfffffffffffffflffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffflffffffffffffffffffffffflgfffffffffflfffffffffffflfffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffflfffffffgflgffffffflflfflfffffflffffffflfffflff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffggfgfffffffflgfffffffffffffffffffffffffffffffffff
fffffflllllfflllffffffffffffffffffffffffffffffffffffffffffffffffffffffffgfgffgffffffffffffflggfffffflffffmmmmffmmfmmfmfmffffffff
fffffflfffffffffllfffllllfffffffffffffffffflfflllllfflllllffffffffffffffffffffffffffffffffflggfffffflfffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffflfflllfllflflfffllllffffffffflffffffffffffffffffffffflfgfffffflffmffffffffffffmfffflffffff
fffffffffffffffffffffffffffffffffffffflfffffffffffffffffflfffffffffffffffffffffffffffffffffflgflfffflffffffmfmfffffffmfflfffffff
fffffflffffffffffffffffffffffffffffffflfffffffffffffffffflfffffffffffffffffffffffffffffffffffglffffflffmfffmmfmmmmfmmmmmmffmffff
fffffflffffffffffffffffffffffffffffffflfffffffffffffffffllffffffffflfffffffffffffffffffffffflgfffffflfffffmmffffffffffffmffmffff
fffffflffffffffffffffffffffffffffffffffflffffffmffffffffflfffffffffflffffffffffffffffffffffflfgffffflffmffmfffffffffffffmffmffff
fffffflfffffffffffffffffflfffffffffffflfffffffffffffffffflffffffffflffgffffffffffffffffffffflfgffffflfffffmfffffffffffffmmfmffff
fffffflfffffffffffffffffflfffffffffffffflfffffffffffffffllfffffffffffffffffffffffgffgffffffflfgffffflfmfffffffffffffffffffffffff
fffffflfffmffffffffffffffffffffffffffffflffffffffmffffffllfffffffffflfgffffffffffffffgfffffflfgffffflfmffffmggffffffffffffffffff
fffffflfffffffffffffffffffffmffffffffflffffffffffffffffffffffffffffffffffffffffffffffgfffffflffffffflfmffmmmffffgggfgffflfffffff
fffffflfffffffffffffffffffffmffffffffffffffffffffffffffflffffffffffflfffffgfffllffffffffffffffffffffffffffffffffffffgffflmffffff
ffffmflfffffffffffffffffffffmfffffffffmffffffffffffffffflffffffffffflffgfffffffffffffgfffffffffffffflfmfffffmfffffffgffffmffffff
ffffmfffffffffffffffffffffffmffffffffffflffffffffffffffflffffffffffflffffffffflffffffffffffffflgffflffmffmfmffffffffgffflfffffff
ffffmffffffffffffffffffffffffffffffffffflfffffffmffffffflffffffffffffffffffffflffffffgffffffffffffflffmffffffffffffgfffffmffffff
ffffffffffffffffffffffffflffmffffffffffffffffffffffffffflffffffffffflfffffffffffffflfgfffffffffgffflffmfffmmmffffffffffflfffffff
fffffflfffffffffffffffffflffmffffffffffflffffmfffffffffflffffffffffffffffffffffffffffffffffflfffgfflffmffffffffffffffffflmfmffff
ffffffffffffffffffffffffffffmffffffffffflffffffffffffffflfffffffffffffffgfffffffffffffffffffffflgffffffffmfgmfmmfmmffmfmmmffffff
ffffffffffffffffffffffffffffmffffffffffflffffffffffffffflfffffffffffffffffffffffffffffffffffffffgfflffmffmffffmfffmggfffffffffff
ffffffflllfffflflfffffllffffmffffffffffffllfffflfffffflllffffffffffffffmgffffffffffgfffffflfffffgfflffmffmffffffffffffffflfmffff
ffffmfffffffffffffffffffffffmffffffffffffffffffffffffffffffffffffffffflfgffflfffflffmmfffffffffgffflffmmmmfmmfmmmfffffffffffffff
ffffffffffffffffffffffffffffmfffffffffffffffffffffffffffffffffffffffffffgfffffffffffffffffgffggffffffllfflffllffffmmmmmmmmmfffff
ffffffffffffffffffffffffffffmfffffffffffffffffffffffffffffffffffffffffffgfffffffffffggfggfffffffffffffffffffffffffffffffffffffff
ffffmfffffffffffffffffffffffmffffffffffffffffffffffffffffffffffffffffffffgffffffffgffffffffffffflfffffffffffffffffflffffflffffff
ffffmfffffffffffffffffffffffmffffffffffffffffffffffffffffffffffffffffffmfgfgfgffffffffffffffffffffffffffffffffffffffflffffffffff
ffffmfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffmmmmmfmmmffffmfffmmfmmmmmfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffflfffffff
fffffffffffffffffffffffffffffffflffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffmffffffffffffffffffffffffffffflffff
fffffffffffflffffffffffffffffffflfffffffllfflfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffflfffffffffffffffflffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffflffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffflfffffflfflffffffffffffflffffffffffffffffffffffffmmfffmfffffffffffffff
fffffflfffffffffffffffffffffffflfffffffffgfgffffffffgfffffffffffflfffffffffffffffffffffffllfffffffffffffffffffffffffmffmffffffff
ffffffgggfffggffgfgggggggfffffflfffffffgffffffffflllfffllfffffffffffffffffffffffffflfffffflffffffffflmfmfmmmfmfmmlffffffffffffff
ffffffglfffffffffffffffffgffffflfffffffllflfffflffffffffffgfffffffffffffffffffflffllllllllllfffffffffffffffmfmffffffffffffffffff
ffffffgfffmffmffffffffffffffffffffffffgfffffffffffffffffflgffffffffffffflllllffffffffflffflfffffffffffmffffffffffffffffflfffmfff
fffffffffffffffffffffffffgfffffffffffffffffffffffffffffflfgfffffffffffffffffffffffffffffffflfffffffffmmfffffffffffffffffffffmfff
ffffffffffffffffffffffffffffffflffffffflffffffffffffffffffgfffffflfffffffllffffffffffflfffflfffffffffmfmffmffffffffmffffffffffff
ffffffgffffffffffffffffffffffflfffffffffffffffflflllllfflfgffffffffffflffffgggggglfffflffffffffffffffmffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffflffffffffffffffflffffffflfggfffffffffffflffffffffflffffffffflfffffffffmfffmfffffffffffffffmffffff
fffffffffffffffffffffmfffgffffffffffffflffffffflffffffflllfffffffffffflfffffffffflffffffffflfffffffffffffffffffffffffffmfmffffff
ffffffflfffffffffffffffffffffflffffffffffffffflfffffffflllfffffffffffflfffffffffflffffffflflfffffffffmfffffffffffffffffffmffffff
fffgffgffffffffffffffffffgffffffffffffgfffffffffffffffflllfffffflfffffffffffffffflffffffffflfffffffffmfffffffffffffffffffmffffff
ffffffflfffffffffffffffffgfffflfffffffffffffffffffffffflflffffffffffffffffffffffffffffffflflfffffffffmmffmfffffffffffffffmffffff
ffffflfffffffffffffffffffgffffffffffffffffffffffffffffllfllffffffffffflfffffffffffffffflffflfffffffffmfffffffffffffffffmfmffffff
ffffflfffffffffffffffffffgfffflfffffffffflfffflffffffflfflffffffffffflfffffffffffffffffllffffffffffffffffffffffffffffflffmffffff
fffffffffffffffffffffffffgffffffffffffffffffffllllfffllllgffffffffffffflffffffffflfffffffffffffffffffmfffffffffffffffffffmffmfff
fffffffffffffffffffffffffgffffffffffffffffffffffffflllfflfffffffffffffffflllffffllffffflffffffffffffffffffffffffffffffffmfffffff
fffffffffffffffffffffffffgfffffffffffgfffffffffffffffffflfffffffffffflflfffflffffffffffllfflfffffffffffffffffffffffffffmmfffffff
fffffffmmfmfmffffffffffffgffflfffffffffffffffffffffffffflffffffffffffffffffffffffffffffllffffffffffffmmfffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffgflfffffffffffffffflmfffffffffffffffffffffffflllllllfflffffffffffmfffffffffffffffffmffmffff
ffffffffffffffffffflflfflgffffffffffffgffggfggfffflffffffmfffffffffffffffffffllllllflllflfflfffffffffmfffffffffmffffmfffmlffffff
ffffffflfllllfflllffggggfgffflffffffffflffffflmmmmmmmmmmfmffffffffffflfffffffffffffffmffffflfmfffffffmfmmfmmmmfmmmmmmfmmmfffffff
fffffmffffffffffffffffffffffflffffffffffffffffffffffffflgmffffflffffflffffffffffffffffffffffffffffffffllffffffffffffffmmffffffff
ffffffffffffffffffffffffffffflllffffffffffffffffffffffflfffffffflffffffffffffffffffffffflfffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffflllffffffffffffffffffffffffffffffffffffffffffffflfffffffffflffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffllfllflffffflffflfffffffffffffffflffffllffllflllfllffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffllflfflffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffflfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

__sfx__
d30100000061000300003000030000300003000030000300003000030000300003000030000300003000030000300003000030000300003000030000300003000030000300003000030000300003000030000300
010100002451000300003000030000300003000030000300003000030000300003000030000300003000030000300003000030000300003000030000300003000030000300003000030000300003000030000300
